name: apna_gadi
description: "A new Flutter project."
publish_to: 'none' # Prevents the package from being accidentally published to pub.dev

version: 1.0.0+1 # Defines the version and build number for your application

environment:
  sdk: '>=3.4.0 <4.0.0' # Specifies the Dart SDK version required

dependencies:
  flutter:
    sdk: flutter # Flutter SDK dependency
  carousel_slider: ^4.0.0 # Carousel slider package for image carousels
  cupertino_icons: ^1.0.6 # Cupertino icons package for iOS style icons
  http: ^0.13.3 # HTTP package for making network requests (check for the latest version)

dev_dependencies:
  flutter_test:
    sdk: flutter # Flutter test package for running tests
  flutter_lints: ^3.0.0 # Package for recommended linting rules

flutter:
  uses-material-design: true # Ensures Material Design is used

  assets:
    - assets/images/app_logo.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png

